version: "3.8"

networks:
    default:
        name: benchmark-network

services:
    benchmark-app:
        container_name: benchmark-app
        image: benchmark-app
        build:
            context: .
            dockerfile: development/dockerfiles/php.dockerfile
        restart: always
        environment:
            TZ: Asia/Bangkok
        networks:
            - default
        volumes:
            - ./src:/var/www/html/benchmark-app
